import localFont from "next/font/local";
import "./globals.css";
<<<<<<< HEAD
import Navbar from "../components/navbar";
=======

>>>>>>> 873ce8817a7ee0ed99a23288973e03f1b44d6139
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <head>
      <link href="./output.css" rel="stylesheet"/>

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-screen h-screen bg-red-500 bg-gradient-to-b from-blue-200 to-red-200">
        <div className="h-24">
        <Navbar />
        
        </div>
        <div className="h-[calc(100vh - 6rem)]">
        {children}
        </div>
        
        
        </div>
=======
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
>>>>>>> 873ce8817a7ee0ed99a23288973e03f1b44d6139
      </body>
    </html>
  );
}
